In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Solar_Energy_Prediction.csv')
df.head()

,temperature_2_m_above_gnd,relative_humidity_2_m_above_gnd,mean_sea_level_pressure_MSL,total_precipitation_sfc,snowfall_amount_sfc,total_cloud_cover_sfc,high_cloud_cover_high_cld_lay,medium_cloud_cover_mid_cld_lay,low_cloud_cover_low_cld_lay,shortwave_radiation_backwards_sfc,wind_speed_10_m_above_gnd,wind_direction_10_m_above_gnd,angle_of_incidence,zenith,azimuth,generated_power_kw
0,2.17,31,1035.0,0.0,0.0,0.0,0,0,0,0.00,6.37,312.71,58.753108,83.237322,128.33543,454.10095
1,2.31,27,1035.1,0.0,0.0,0.0,0,0,0,1.78,5.15,294.78,45.408585,75.143041,139.65530,1411.99940
2,3.65,33,1035.4,0.0,0.0,0.0,0,0,0,108.58,4.68,270.00,32.848282,68.820648,152.53769,2214.84930
3,5.82,30,1035.4,0.0,0.0,0.0,0,0,0,258.10,3.60,323.13,22.699288,64.883536,166.90159,2527.60920
4,7.73,27,1034.4,0.0,0.0,0.0,0,0,0,375.58,6.21,10.01,19.199908,63.795208,182.13526,2640.20340

In [4]:
## Z-Score
from scipy import stats

z_scores = np.abs(stats.zscore(df))
df_no_outliers = df[(z_scores <3).all(axis=1)]

In [13]:
df_no_outliers

,temperature_2_m_above_gnd,relative_humidity_2_m_above_gnd,mean_sea_level_pressure_MSL,total_precipitation_sfc,snowfall_amount_sfc,total_cloud_cover_sfc,high_cloud_cover_high_cld_lay,medium_cloud_cover_mid_cld_lay,low_cloud_cover_low_cld_lay,shortwave_radiation_backwards_sfc,wind_speed_10_m_above_gnd,wind_direction_10_m_above_gnd,angle_of_incidence,zenith,azimuth,generated_power_kw
0,2.17,31,1035.0,0.0,0.0,0.0,0,0,0,0.00,6.37,312.71,58.753108,83.237322,128.33543,454.100950
1,2.31,27,1035.1,0.0,0.0,0.0,0,0,0,1.78,5.15,294.78,45.408585,75.143041,139.65530,1411.999400
2,3.65,33,1035.4,0.0,0.0,0.0,0,0,0,108.58,4.68,270.00,32.848282,68.820648,152.53769,2214.849300
3,5.82,30,1035.4,0.0,0.0,0.0,0,0,0,258.10,3.60,323.13,22.699288,64.883536,166.90159,2527.609200
4,7.73,27,1034.4,0.0,0.0,0.0,0,0,0,375.58,6.21,10.01,19.199908,63.795208,182.13526,2640.203400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4208,8.69,66,1025.1,0.0,0.0,100.0,100,100,100,257.21,21.66,285.42,22.700907,64.952098,167.06794,173.410560
4209,7.57,90,1026.1,0.0,0.0,100.0,79,100,100,210.04,11.97,6.91,19.307487,63.895118,182.28247,403.792220
4210,7.27,90,1026.3,0.1,0.0,100.0,73,100,100,113.92,9.01,2.29,25.249506,65.827032,197.33868,158.367780
4211,8.25,81,1025.5,0.0,0.0,100.0,74,66,100,186.90,7.34,11.31,36.361161,70.496313,211.30027,126.953060
4212,8.00,80,1025.3,0.0,0.0,100.0,100,100,100,172.66,11.44,12.72,48.452849,76.919574,223.04931,20.055031

In [5]:
df_no_outliers

,temperature_2_m_above_gnd,relative_humidity_2_m_above_gnd,mean_sea_level_pressure_MSL,total_precipitation_sfc,snowfall_amount_sfc,total_cloud_cover_sfc,high_cloud_cover_high_cld_lay,medium_cloud_cover_mid_cld_lay,low_cloud_cover_low_cld_lay,shortwave_radiation_backwards_sfc,wind_speed_10_m_above_gnd,wind_direction_10_m_above_gnd,angle_of_incidence,zenith,azimuth,generated_power_kw
0,2.17,31,1035.0,0.0,0.0,0.0,0,0,0,0.00,6.37,312.71,58.753108,83.237322,128.33543,454.100950
1,2.31,27,1035.1,0.0,0.0,0.0,0,0,0,1.78,5.15,294.78,45.408585,75.143041,139.65530,1411.999400
2,3.65,33,1035.4,0.0,0.0,0.0,0,0,0,108.58,4.68,270.00,32.848282,68.820648,152.53769,2214.849300
3,5.82,30,1035.4,0.0,0.0,0.0,0,0,0,258.10,3.60,323.13,22.699288,64.883536,166.90159,2527.609200
4,7.73,27,1034.4,0.0,0.0,0.0,0,0,0,375.58,6.21,10.01,19.199908,63.795208,182.13526,2640.203400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4208,8.69,66,1025.1,0.0,0.0,100.0,100,100,100,257.21,21.66,285.42,22.700907,64.952098,167.06794,173.410560
4209,7.57,90,1026.1,0.0,0.0,100.0,79,100,100,210.04,11.97,6.91,19.307487,63.895118,182.28247,403.792220
4210,7.27,90,1026.3,0.1,0.0,100.0,73,100,100,113.92,9.01,2.29,25.249506,65.827032,197.33868,158.367780
4211,8.25,81,1025.5,0.0,0.0,100.0,74,66,100,186.90,7.34,11.31,36.361161,70.496313,211.30027,126.953060
4212,8.00,80,1025.3,0.0,0.0,100.0,100,100,100,172.66,11.44,12.72,48.452849,76.919574,223.04931,20.055031

In [16]:
## IQR

Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)

IQR = Q3 - Q1

df_iqr = df[~((df < (Q1 - 1.5*IQR)) | (df > (Q3 + 1.5*IQR))).any(axis=1)]

In [17]:
df_iqr

,temperature_2_m_above_gnd,relative_humidity_2_m_above_gnd,mean_sea_level_pressure_MSL,total_precipitation_sfc,snowfall_amount_sfc,total_cloud_cover_sfc,high_cloud_cover_high_cld_lay,medium_cloud_cover_mid_cld_lay,low_cloud_cover_low_cld_lay,shortwave_radiation_backwards_sfc,wind_speed_10_m_above_gnd,wind_direction_10_m_above_gnd,angle_of_incidence,zenith,azimuth,generated_power_kw
0,2.17,31,1035.0,0.0,0.0,0.0,0,0,0,0.00,6.37,312.71,58.753108,83.237322,128.33543,454.10095
1,2.31,27,1035.1,0.0,0.0,0.0,0,0,0,1.78,5.15,294.78,45.408585,75.143041,139.65530,1411.99940
2,3.65,33,1035.4,0.0,0.0,0.0,0,0,0,108.58,4.68,270.00,32.848282,68.820648,152.53769,2214.84930
3,5.82,30,1035.4,0.0,0.0,0.0,0,0,0,258.10,3.60,323.13,22.699288,64.883536,166.90159,2527.60920
4,7.73,27,1034.4,0.0,0.0,0.0,0,0,0,375.58,6.21,10.01,19.199908,63.795208,182.13526,2640.20340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4199,9.83,49,1025.7,0.0,0.0,1.5,5,0,0,372.02,13.10,164.05,22.695630,64.999055,167.20119,2581.48000
4200,11.91,44,1025.2,0.0,0.0,1.5,5,0,0,436.99,12.02,171.38,19.386698,63.967382,182.40231,2530.46170
4201,12.85,44,1024.2,0.0,0.0,0.6,2,0,0,451.23,11.09,166.87,25.374190,65.920880,197.43695,2109.43030
4202,12.87,46,1024.2,0.0,0.0,2.7,9,0,0,418.30,18.43,167.59,36.490199,70.605886,211.37427,731.07806
4203,11.54,54,1023.9,0.0,0.0,6.6,22,0,0,339.09,21.96,179.06,49.353298,77.504836,223.76691,88.52250

In [1]:
temperature_2_m_above_gnd   = 25
relative_humidity_2_m_above_gnd   = 70
mean_sea_level_pressure_MSL   = 1000
total_precipitation_sfc   = 3.00
snowfall_amount_sfc   = 1.5
total_cloud_cover_sfc   = 40
high_cloud_cover_high_cld_lay   = 0.0
medium_cloud_cover_mid_cld_lay   = 0.0
low_cloud_cover_low_cld_lay   = 0.0
shortwave_radiation_backwards_sfc   = 258.1
wind_speed_10_m_above_gnd   = 3.9
wind_direction_10_m_above_gnd   = 320.0
angle_of_incidence   = 23
zenith   = 65
azimuth   = 165.00

In [2]:
import numpy as np
import pandas as pd 

input_data = pd.DataFrame({
    'temperature_2_m_above_gnd': [temperature_2_m_above_gnd],
    'relative_humidity_2_m_above_gnd': [relative_humidity_2_m_above_gnd],
    'mean_sea_level_pressure_MSL': [mean_sea_level_pressure_MSL],
    'total_precipitation_sfc': [total_precipitation_sfc],
    'snowfall_amount_sfc': [snowfall_amount_sfc],
    'total_cloud_cover_sfc': [total_cloud_cover_sfc],
    'high_cloud_cover_high_cld_lay': [high_cloud_cover_high_cld_lay],
    'medium_cloud_cover_mid_cld_lay': [medium_cloud_cover_mid_cld_lay],
    'low_cloud_cover_low_cld_lay': [low_cloud_cover_low_cld_lay],
    'shortwave_radiation_backwards_sfc': [shortwave_radiation_backwards_sfc],
    'wind_speed_10_m_above_gnd': [wind_speed_10_m_above_gnd],
    'wind_direction_10_m_above_gnd': [wind_direction_10_m_above_gnd],
    'angle_of_incidence': [angle_of_incidence],
    'zenith': [zenith],
    'azimuth': [azimuth]
})

print(type(input_data))

<class 'pandas.core.frame.DataFrame'>

In [3]:
input_data

,temperature_2_m_above_gnd,relative_humidity_2_m_above_gnd,mean_sea_level_pressure_MSL,total_precipitation_sfc,snowfall_amount_sfc,total_cloud_cover_sfc,high_cloud_cover_high_cld_lay,medium_cloud_cover_mid_cld_lay,low_cloud_cover_low_cld_lay,shortwave_radiation_backwards_sfc,wind_speed_10_m_above_gnd,wind_direction_10_m_above_gnd,angle_of_incidence,zenith,azimuth
0,25,70,1000,3.0,1.5,40,0.0,0.0,0.0,258.1,3.9,320.0,23,65,165.0

In [5]:
import pickle 

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

with open('model1.pkl', 'rb') as file:
    model = pickle.load(file)

input_data_scaled = scaler.transform(input_data)
input_data_scaled

array([[ 0.86072309,  1.22423508, -3.13624748,  3.        ,  1.5       ,
         8.26771584, -0.32534969, -0.32499792, -0.37757933, -0.71099904,
        -1.34199188,  1.18640351, -1.0710207 ,  0.36961961, -0.07643127]])

In [7]:
prediction = model.predict(input_data_scaled)
prediction[0]

1305.5178795437498